# Numpy is a library that allows for the use of arrays and matrices

In [36]:
import numpy as np

In [37]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [38]:
type(a)
type(b)

numpy.ndarray

In [39]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Creating a 2D array

In [40]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


Creating 3D arrays

In [41]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Methods of array

In [42]:
print(a.dtype)

int64


To get the number of dimensions of an array 

In [43]:
print(a.ndim)

2


In [44]:
print(a.shape)

(2, 3)


In [45]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [47]:
np.arange(2,22)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [48]:
np.random.randint(10,30)

15

In [49]:
np.random.rand(10,30)

array([[0.90434715, 0.66664006, 0.48114136, 0.72011584, 0.74425533,
        0.67887212, 0.01347026, 0.63788366, 0.92847813, 0.22402855,
        0.79449014, 0.33122738, 0.38219391, 0.35506013, 0.72195121,
        0.89296242, 0.48847702, 0.30889966, 0.40608455, 0.72508575,
        0.41841057, 0.77341862, 0.68078088, 0.38370231, 0.28001088,
        0.12920051, 0.93788478, 0.90148226, 0.54094952, 0.85660033],
       [0.67116766, 0.6413212 , 0.13826197, 0.81534314, 0.10909285,
        0.38352866, 0.17398476, 0.21710455, 0.11888166, 0.53656704,
        0.96061333, 0.26020349, 0.68072357, 0.24588228, 0.07412329,
        0.4698397 , 0.84062657, 0.15868639, 0.85973366, 0.20800815,
        0.40209405, 0.70991646, 0.83057086, 0.9991223 , 0.45555396,
        0.38443657, 0.13579001, 0.82270009, 0.92745461, 0.29647932],
       [0.41613937, 0.55288455, 0.05418986, 0.18041389, 0.35741734,
        0.52295362, 0.65740155, 0.09358839, 0.9724871 , 0.30967216,
        0.07341891, 0.7577121 , 0.16640758, 0.

In [50]:
np.random.randint(10,30, size=(3,3))

array([[23, 16, 12],
       [25, 21, 10],
       [27, 12, 21]], dtype=int32)

In [51]:
x = np.array([[7,2,3],[2,5,2],[3,5,1]])
y = np.array([[1,8,3],[3,7,2],[2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


Matrices Multiplication

In [52]:
print(x@y)

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [53]:
print(x.dot(y))

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [54]:
x.prod()

np.int64(12600)

In [55]:
x.mean()

np.float64(3.3333333333333335)

In [56]:
x.mean(axis=0)

array([4., 4., 2.])

In [57]:
x.mean(axis=1)

array([4., 3., 3.])

In [59]:
print(x.sum())
print(x.var())
print(x.std())

30
3.3333333333333335
1.8257418583505538


In [61]:
z = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(z, 25)) #25th percentile
print(np.percentile(z, 50)) #50th percentile
print(np.percentile(z, 75)) #75th percentile

3.0
5.0
7.0


In [64]:
arr = np.random.randint(10,50, size=(14,14))
print(arr)

[[18 30 46 20 18 44 15 32 40 35 24 30 42 22]
 [37 26 25 31 36 13 36 24 24 37 47 30 21 27]
 [15 39 33 41 47 16 48 28 18 19 26 27 34 24]
 [44 31 33 49 41 15 39 45 12 22 31 45 23 38]
 [28 42 45 13 46 39 22 31 17 34 25 23 32 18]
 [29 15 38 19 25 20 44 22 47 32 36 30 19 18]
 [29 42 43 39 42 29 31 28 23 11 47 49 18 43]
 [15 14 36 22 11 15 31 41 39 30 10 24 20 30]
 [29 40 14 36 11 30 21 18 32 30 48 39 32 20]
 [44 35 39 27 20 49 12 13 21 10 14 20 39 20]
 [26 25 12 40 11 17 49 18 42 22 24 10 11 34]
 [47 37 15 32 17 16 11 48 13 43 13 28 26 49]
 [49 20 37 20 15 36 49 49 11 37 28 44 49 40]
 [10 35 27 26 11 26 43 23 41 28 33 19 14 23]]


In [68]:
print('2x8')
print(arr.reshape(2,8))

2x8


ValueError: cannot reshape array of size 196 into shape (2,8)

In [69]:
print(x[0])
print(x[1])

[7 2 3]
[2 5 2]


In [70]:
print(x[0,0])

7


In [71]:
print(x[0,1])

2
